---
version: "3.8"

services:

  image_gallery:
    image: "szb0151/image_gallery-m7"
    environment:
      PG_HOST: "database"
      IG_USER: "image_gallery"
      IG_PASSWD_FILE: "/run/secrets/ig_password"
      IG_DATABASE: "image_gallery"
      S3_IMAGE_BUCKET: "edu.au.cc.ram-image-gallery-config"
    ports:
      - "80:5000"
    secrets:
      - ig_password
    deploy:
      replicas: 4
    depends_on:
      - "database"

  database:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/ig_password"
      POSTGRES_USER: image_gallery
      POSTGRES_DB: image_gallery
      PGDATA: "/var/lib/postgresql/data/pgdata"
    secrets:
      - ig_password
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - node.labels.database==yes
    volumes:
      - "/mnt/efs:/var/lib/postgresql/data"
      - "/home/ec2-user/java-image-gallery/init:/docker-entrypoint-initdb.d"

volumes:
  image-gallery-postgres:

secrets:
  ig_password:
    external: true
