/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import edu.au.cc.gallery.tools.UserAdmin;
import java.util.Scanner;

public class App {

  public static void main(String[] args) throws Exception {
      UserAdmin.accessDB();
  }
}
